package config

import (
	"os"
)

func Load() (*Config, error) {
	cfg := &Config{
		Port:           getEnv("PORT", "8080"),
		WireGuardIface: getEnv("WG_INTERFACE", "wg0"),
		WireGuardPort:  51820,
		NetworkCIDR:    getEnv("NETWORK_CIDR", "10.8.0.0/24"),
		AllowedIPs:     "0.0.0.0/0",
		DNSServers:     []string{"1.1.1.1", "8.8.8.8"},
		Servers: []ServerConfig{
			{Code: "KE", Name: "Kenya", IP: getEnv("SERVER_IP", "")},
			{Code: "US", Name: "United States", IP: "192.168.43.112"},
			{Code: "UK", Name: "United Kingdom", IP: ""},
		},
	}

	// Generate keys if not exist
	privateKey := getEnv("WG_PRIVATE_KEY", "")
	publicKey := getEnv("WG_PUBLIC_KEY", "")

	if privateKey == "" || publicKey == "" {
		// Will be generated by wireguard service
		cfg.ServerPrivateKey = ""
		cfg.ServerPublicKey = ""
	} else {
		cfg.ServerPrivateKey = privateKey
		cfg.ServerPublicKey = publicKey
	}

	return cfg, nil
}

func getEnv(key, defaultValue string) string {
	if value := os.Getenv(key); value != "" {
		return value
	}
	return defaultValue
}
