package config

import (
	"os"
	"p2nova-vpn/internal/geo"
)

func Load() (*Config, error) {
	cfg := &Config{
		Port:           getEnv("PORT", "8080"),
		WireGuardIface: getEnv("WG_INTERFACE", "wg0"),
		WireGuardPort:  51820,
		NetworkCIDR:    getEnv("NETWORK_CIDR", "10.8.0.0/24"),
		AllowedIPs:     "0.0.0.0/0",
		DNSServers:     []string{"1.1.1.1", "8.8.8.8"},
	}

	geoInfo, err := geo.GetServerGeo(os.Getenv("SERVER_IP"))
	if err != nil {
		geoInfo = &GeoInfo{Country: "Unknown", IP: os.Getenv("SERVER_IP")}
	}

	cfg.Servers = []ServerConfig{
		{
			Code: geoInfo.Country,
			Name: geoInfo.City + " VPN",
			IP:   geoInfo.IP,
		},
	}
	// Generate keys if not exist
	privateKey := getEnv("WG_PRIVATE_KEY", "")
	publicKey := getEnv("WG_PUBLIC_KEY", "")

	if privateKey == "" || publicKey == "" {
		// Will be generated by wireguard service
		cfg.ServerPrivateKey = ""
		cfg.ServerPublicKey = ""
	} else {
		cfg.ServerPrivateKey = privateKey
		cfg.ServerPublicKey = publicKey
	}

	return cfg, nil
}

func getEnv(key, defaultValue string) string {
	if value := os.Getenv(key); value != "" {
		return value
	}
	return defaultValue
}
